---
- hosts:  all
  remote_user: root
  gather_facts: true
  vars:
    public_key_file: "/root/ansible_user.pub"
    temp_public_key_file: "/tmp/public_key_file.key"

  tasks:

  ## Create the Ansible users and groups
    - name: Create the Ansible group
      group:
        name: ansible
        state: present
        gid: 1337

    - name: Create the Ansible user
      user:
        name: ansible
        comment: "Ansible service account"
        uid: 1337
        group: ansible
        generate_ssh_key: yes
        state: present

    - name: Copy public key to the host
      copy:
        src: {{ public_key_file }}
        dest: {{ temp_public_key_file }}
        owner: ansible
        group: ansible
        mode: 0644

  ##
  ## Clean the Ansible users and groups
    - name: Remove the Ansible user
      user:
        name: ansible
        state: absent
      tags:
        - clean

    - name: Remove the Ansible group
      group:
        name: ansible
        state: absent
      tags:
        - clean






