---
- hosts:  all
  remote_user: root
  gather_facts: true

  tasks:
  - name: Create the Ansible user
    user:
    - name: ansible
    - comment: "Ansible service account"
    - uid: 1337
    - group: ansible
    - generate_ssh_key: yes


