---
- hosts:  all
  remote_user: root
  gather_facts: true

  tasks:

  ## Create the Ansible users and groups
    - name: Create the Ansible group
      group:
        name: ansible
        state: present
        gid: 1337

    - name: Create the Ansible user
      user:
        name: ansible
        comment: "Ansible service account"
        uid: 1337
        group: ansible
        generate_ssh_key: yes
        state: present

    - name: Copy public key to the host
      copy:
        src: /root/ansible_user.pub
        dest: /tmp/public_key_file.key
        owner: ansible
        group: ansible
        mode: 0644

  ##
  ## Clean the Ansible users and groups
    - name: Remove the Ansible user
      user:
        name: ansible
        state: absent
      tags:
        - clean

    - name: Remove the Ansible group
      group:
        name: ansible
        state: absent
      tags:
        - clean






