---
- hosts:  all
  remote_user: root
  gather_facts: true

  tasks:
    - name: Create the Ansible group
      group:
        name: ansible
        state: present
        gid: 1337

    - name: Remove the Ansible group
      group:
        name: ansible
        state: absent
      tags:
        - clean

    - name: Create the Ansible user
      user:
        name: ansible
        comment: "Ansible service account"
        uid: 1337
        group: ansible
        generate_ssh_key: yes
        state: present


    - name: Remove the Ansible user
      user:
        name: ansible
        state: absent
      tags:
        - clean

