---
- hosts:  all
  remote_user: root
  gather_facts: true
  defaults:
    new_username: answorker
    new_groupname: answorker

  tasks:

  ## Create the Ansible users and groups
    - name: Create the Ansible group
      group:
        name: {{ new_groupname }}
        state: present
        gid: 1337

    - name: Create the Ansible user
      user:
        name: {{ new_username }}
        comment: "Ansible service account"
        uid: 1337
        group: {{ new_groupname }}
        generate_ssh_key: yes
        state: present

#    - name: Copy public key to the host
#      copy:
#        src: /tmp/ansible_user.pub
#        dest: /tmp/public_key_file.key
#        owner: {{ new_username }}
#        group: {{ new_groupname }}
#        mode: 0644

  ##
  ## Clean the Ansible users and groups
    - name: Remove the Ansible user
      user:
        name: {{ new_username }}
        state: absent
      tags:
        - clean

    - name: Remove the Ansible group
      group:
        name: {{ new_groupname }}
        state: absent
      tags:
        - clean






